spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 123456
    hikari:
      maximum-pool-size: 50
server:
  port: 80
