server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
#  elasticsearch:
#    uris: http://localhost:9200
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tbl_
