spring:
  profiles:
    active: test
---
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 80
---
spring:
  profiles: dev
server:
  port: 81
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82