server:
  port: 8080
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tbl_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  cache:
    type: redis
    redis:
      time-to-live: 10s
      use-key-prefix: true
      key-prefix: sms_
      cache-null-values: false
  redis:
    host: 192.168.56.1
    port: 9527