server:
  port: 80
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tbl_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
jetcache:
  statIntervalMinutes: 1
  valueEncode: java
  valueDecode: java
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      host: 192.168.56.1
      port: 9527
      keyConvertor: fastjson
      poolConfig:
        maxTotal: 50
    sms:
      type: redis
      host: 192.168.56.1
      port: 9527
      poolConfig:
        maxTotal: 50
