server:
  port: 80
logging:
  group:
    ebanK: com.kk.controller,com.kk.service,com.kk.mapper
    iservice: com.alibaba
  level:
    com.kk.controller: debug
    root: debug
    ebank: debug
  pattern:
    console: "%d - %clr(%p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
    #console: "%d - %m%n"